### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by LeoDJ** [open-eats/open-eats.github.io#1]
The demo is currently broken and shows a blank page.

Probably because the script path is wrong and results in a 301. I'm not sure if this is the only thing that's not working tho.
It probably should be only `/bundle.js` instead of `/open-eats.github.io/bundle.js`.

![grafik](https://user-images.githubusercontent.com/5898657/120945895-0244e700-c73b-11eb-8b73-c2b24b9188c4.png)

**Comment by codefaux** [comment]
Might be ideal to fix this some day. I considered switching to OpenEats but can't find screenshots or a link to the demo on the main repo, can only find an issue reporting that the site is broken.

Follow that issue to this issue, no solution.

It's been a smidge over three months, is this project dead? Should I abandon consideration to use it? Not a good look.

**Comment by rustymyers** [comment]
All, the project is mostly dead. I have rights to do updates, but don't have experience developing this product so might not be quick to fix things. Help appreciated!

**Comment by rustymyers** [comment]
After I read your comment again, I was able to confirm and fix the issue with the demo site. Thanks!!

**Comment by protist** [comment]
FWIW this is not entirely fixed. "Internal" links still open a blank page.
